### ISSUE TITLE
Button broken on alt account, craftscan tab not on profession pane

### ISSUE THREAD

**Issue by Ammastusx** [stevin05/CraftScan#27]
Hi, I configured the addon and it was working. I logged out and exited the game on my alt account and now when I click the button it won't open the craftscan tab. I do get pings still, but I'm unable to see the UI. 

https://imgur.com/a/oQoIynN

![image](https://github.com/user-attachments/assets/c11a352c-51df-4f85-8e67-38b3a3cc1a93)

Though its still connected to my other account.

**Comment by ZyborgRSA** [comment]
Similar issue for me, button doesn't load at all on relog/reload either. When I change something on main account, it throws error on second account, but still can't open craftscan on it. Error from Bugsack:
17x CraftScan/ChatScanner.lua:173: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@CraftScan/ChatScanner.lua"]:173: in function `LoadConfig'
[string "@CraftScan/OrderPage.lua"]:1257: in function `OnCrafterListModified'
[string "@CraftScan/Utils/Comm.lua"]:283: in function <CraftScan/Utils/Comm.lua:241>
[string "@CraftScan/Utils/Comm.lua"]:1204: in function <CraftScan/Utils/Comm.lua:1166>
[string "@CraftScan/Utils/Comm.lua"]:1249: in function <CraftScan/Utils/Comm.lua:1243>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by ZyborgRSA** [comment]
If it helps I just deleted the WTF file for Craftscan on the second account and re-synced it, seems fine now

**Comment by stevin05** [comment]
I'm guessing this has to do with AA shuffling. The account link code is not properly handling learning a profession while both accounts are online. If you learn a profession, open it, don't touch any CraftScan config items, then toggle anything on the Crafter List to enable/disable scanning for that character, it only sends part of the config and I was able to hit this error.

Does that sound like a possibility? Going to move forward with fixing that as well as adding an upgrade task to clean up any misconfigs caused by this in WTF files. If you ever hit this type of thing again, a reload will likely fix it with this new cleanup task.

**Comment by ZyborgRSA** [comment]
Very possible, was also jumping between characters quite a lot when I was setting it up. Thanks for taking a look. Appreciate the work! Great addon
